package com.brielage.uitleendienst.controllers;

import com.brielage.uitleendienst.authorization.OriginChecker;
import com.brielage.uitleendienst.models.ContactMagazijn;
import com.brielage.uitleendienst.models.Magazijn;
import com.brielage.uitleendienst.models.Persoon;
import com.brielage.uitleendienst.repositories.ContactMagazijnRepository;
import com.brielage.uitleendienst.repositories.MagazijnRepository;
import com.brielage.uitleendienst.repositories.PersoonRepository;
import com.brielage.uitleendienst.responses.Responder;
import com.brielage.uitleendienst.tools.APILogger;
import com.brielage.uitleendienst.tools.RemoveDuplicates;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

@SuppressWarnings ("rawtypes")
@RestController
@RequestMapping (value = "/contactmagazijn")
public class ContactMagazijnController {
    @SuppressWarnings ("SpringJavaAutowiredFieldsWarningInspection")
    @Autowired
    private ContactMagazijnRepository contactMagazijnRepository;
    @SuppressWarnings ("SpringJavaAutowiredFieldsWarningInspection")
    @Autowired
    private PersoonRepository         persoonRepository;
    @SuppressWarnings ("SpringJavaAutowiredFieldsWarningInspection")
    @Autowired
    private MagazijnRepository        magazijnRepository;

    @GetMapping (value = { "/", "" })
    public ResponseEntity findByProperties (
            @RequestParam (required = false) List<String> persoonId,
            @RequestParam (required = false) List<String> magazijnId,
            @RequestHeader ("Authorization") String token,
            @RequestHeader ("Origin") String origin) {
        APILogger.logRequest("contactMagazijn.get*");

        if (!OriginChecker.checkOrigin(origin))
            return Responder.respondBadRequest("origin not allowed " + origin);

        if ((persoonId == null || persoonId.isEmpty())
                && (magazijnId == null || magazijnId.isEmpty())) {
            APILogger.logRequest("contactmagazijn.findAll");
            List<ContactMagazijn> contactMagazijnen = contactMagazijnRepository.findAll();

            if (contactMagazijnen.isEmpty()) return Responder.respondNotFound();

            return Responder.respondOk(contactMagazijnen);
        }

        List<ContactMagazijn> contactMagazijnen = new ArrayList<>();

        if (persoonId != null && !persoonId.isEmpty()) {
            APILogger.logRequest("contactmagazijn.findAllByPersoonIdIsIn");
            contactMagazijnen.addAll(contactMagazijnRepository.findAllByPersoonIdIsIn(persoonId));
        }

        if (magazijnId != null && !magazijnId.isEmpty()) {
            APILogger.logRequest("contactmagazijn.findAllByMagazijnIdIsIn");
            contactMagazijnen.addAll(contactMagazijnRepository.findAllByMagazijnIdIsIn(magazijnId));
        }


        if (contactMagazijnen.isEmpty()) return Responder.respondNotFound();

        //remove duplicates
        contactMagazijnen = RemoveDuplicates.removeDuplicates(contactMagazijnen);

        return Responder.respondOk(contactMagazijnen);
    }

    @GetMapping ("/{id}")
    public ResponseEntity findById (
            @PathVariable String id,
            @RequestHeader ("Authorization") String token,
            @RequestHeader ("Origin") String origin) {
        APILogger.logRequest("contactmagazijn.findById", id);

        if (!OriginChecker.checkOrigin(origin))
            return Responder.respondBadRequest("origin not allowed " + origin);

        Optional<ContactMagazijn> c = contactMagazijnRepository.findById(id);

        if (c.isEmpty()) return Responder.respondNotFound();

        return Responder.respondOk(c.get());
    }

    @PostMapping (value = { "/", "" })
    public ResponseEntity create (
            @RequestBody ContactMagazijn contactMagazijn,
            @RequestHeader ("Authorization") String token,
            @RequestHeader ("Origin") String origin) {
        APILogger.logRequest("contactMagazijn.create", contactMagazijn.toString());

        if (!OriginChecker.checkOrigin(origin))
            return Responder.respondBadRequest("origin not allowed " + origin);

        try {
            if (!validateContactMagazijn(contactMagazijn))
                return Responder.respondBadRequest("not valid");

            Optional<ContactMagazijn> optionalContactMagazijn =
                    contactMagazijnRepository.findByMagazijnIdAndPersoonId(
                            contactMagazijn.getMagazijnId(), contactMagazijn.getPersoonId());

            if (optionalContactMagazijn.isPresent())
                return Responder.respondBadRequest("already present");

            // ignore ID when creating, will get automagically generated by DB
            contactMagazijn.setId(null);
            ContactMagazijn c = contactMagazijnRepository.save(contactMagazijn);

            return Responder.respondCreated(c);
        } catch (Exception e) {
            APILogger.logException(e.getMessage());
            return Responder.respondBadRequest(e.getMessage());
        }
    }

    @PutMapping (value = "/{id}")
    public ResponseEntity put (
            @PathVariable String id,
            @RequestBody ContactMagazijn contactMagazijn,
            @RequestHeader ("Authorization") String token,
            @RequestHeader ("Origin") String origin) {
        APILogger.logRequest("contactMagazijn.put", id);

        if (!OriginChecker.checkOrigin(origin))
            return Responder.respondBadRequest("origin not allowed " + origin);

        try {
            if (!validateContactMagazijnId(contactMagazijn))
                return Responder.respondBadRequest("not valid");

            Optional<ContactMagazijn> c = contactMagazijnRepository.findById(id);

            if (c.isEmpty())
                return Responder.respondNotFound();

            contactMagazijn.setId(c.get()
                                   .getId());
            ContactMagazijn result = contactMagazijnRepository.save(contactMagazijn);

            return Responder.respondCreated(result);
        } catch (Exception e) {
            return Responder.respondBadRequest(e.getMessage());
        }
    }

    @DeleteMapping (value = "/{id}")
    public ResponseEntity delete (
            @PathVariable String id,
            @RequestHeader ("Authorization") String token,
            @RequestHeader ("Origin") String origin) {
        APILogger.logRequest("uitleenbaarItem.delete", id);

        if (!OriginChecker.checkOrigin(origin))
            return Responder.respondBadRequest("origin not allowed " + origin);

        try {
            Optional<ContactMagazijn> c = contactMagazijnRepository.findById(id);

            if (c.isEmpty())
                return Responder.respondNotFound();

            contactMagazijnRepository.delete(c.get());

            return Responder.respondNoContent("deleted");
        } catch (Exception e) {
            return Responder.respondBadRequest(e.getMessage());
        }
    }

    private boolean validateContactMagazijnId (ContactMagazijn c) {
        if (c.getId()
             .isEmpty())
            return false;
        return validateContactMagazijn(c);
    }

    private boolean validateContactMagazijn (ContactMagazijn c) {
        return validatePersoonId(c.getPersoonId())
                && validateMagazijnId(c.getMagazijnId());
    }

    private boolean validatePersoonId (String persoonId) {
        if (persoonId == null || persoonId.isEmpty()) return false;
        Optional<Persoon> p = persoonRepository.findById(persoonId);
        return p.isPresent();
    }

    private boolean validateMagazijnId (String magazijnId) {
        if (magazijnId == null || magazijnId.isEmpty()) return false;
        Optional<Magazijn> m = magazijnRepository.findById(magazijnId);
        return m.isPresent();
    }

}
