package com.brielage.uitleendienst.controllers;

import com.brielage.uitleendienst.models.Magazijn;
import com.brielage.uitleendienst.repositories.MagazijnRepository;
import com.brielage.uitleendienst.tools.APILogger;
import com.brielage.uitleendienst.tools.RemoveDuplicates;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

@RestController
@RequestMapping (value = "/magazijn")
public class MagazijnController {
    @SuppressWarnings ("SpringJavaAutowiredFieldsWarningInspection")
    @Autowired
    private MagazijnRepository magazijnRepository;

    @GetMapping (value = { "/", "" })
    public ResponseEntity findByProperties (
            @RequestParam (required = false) List<String> naam,
            @RequestParam (required = false) List<String> email) {
        if ((naam == null || naam.isEmpty())
                && (email == null || email.isEmpty())) {
            List<Magazijn> magazijnen = magazijnRepository.findAll();

            if (magazijnen.isEmpty())
                return ResponseEntity.notFound()
                                     .build();

            return ResponseEntity.ok()
                                 .body(magazijnen);
        }

        List<Magazijn> magazijnen = new ArrayList<>();

        if (naam != null && !naam.isEmpty())
            magazijnen.addAll(magazijnRepository.findAllByNaamIsIn(naam));
        if (email != null && !email.isEmpty())
            magazijnen.addAll(magazijnRepository.findAllByEmailIsIn(email));

        magazijnen = RemoveDuplicates.removeDuplicates(magazijnen);

        if (magazijnen.isEmpty())
            return ResponseEntity.notFound()
                                 .build();

        return ResponseEntity.ok()
                             .body(magazijnen);
    }

    @GetMapping ("/{id}")
    public ResponseEntity findById (@PathVariable String id) {
        Optional<Magazijn> m = magazijnRepository.findById(id);

        if (m.isPresent())
            return ResponseEntity.ok()
                                 .body(m.get());

        return ResponseEntity.notFound()
                             .build();
    }

    @PostMapping (value = { "/", "" })
    public ResponseEntity create (@RequestBody Magazijn magazijn) {
        try {
            if (!validateMagazijn(magazijn))
                return ResponseEntity.badRequest()
                                     .build();

            // ignore ID when creating, will get automagically generated by DB
            magazijn.setId(null);
            Magazijn m = magazijnRepository.save(magazijn);

            return new ResponseEntity(m, HttpStatus.CREATED);
        } catch (Exception e) {
            return ResponseEntity.badRequest()
                                 .build();
        }
    }

    @PutMapping (value = "/{id}")
    public ResponseEntity put (
            @PathVariable String id,
            @RequestBody Magazijn magazijn) {
        try {
            if (!validateMagazijnId(magazijn))
                return ResponseEntity.badRequest()
                                     .build();

            Optional<Magazijn> m = magazijnRepository.findById(id);

            if (m.isEmpty())
                return ResponseEntity.notFound()
                                     .build();

            magazijn.setId(m.get()
                            .getId());
            Magazijn result = magazijnRepository.save(magazijn);

            return new ResponseEntity(result, HttpStatus.CREATED);
        } catch (Exception e) {
            return ResponseEntity.badRequest()
                                 .build();
        }
    }

    @DeleteMapping (value = "/{id}")
    public ResponseEntity delete (@PathVariable String id) {
        try {
            Optional<Magazijn> m = magazijnRepository.findById(id);

            if (m.isEmpty())
                return ResponseEntity.badRequest()
                                     .build();

            magazijnRepository.delete(m.get());

            return ResponseEntity.noContent()
                                 .build();
        } catch (Exception e) {
            return ResponseEntity.badRequest()
                                 .build();
        }
    }

    private boolean validateMagazijnId (Magazijn m) {
        if (m.getId()
             .isEmpty())
            return false;
        return validateMagazijn(m);
    }

    private boolean validateMagazijn (Magazijn m) {
        return validateNaam(m.getNaam())
                && validateAdres(m.getAdres())
                && validateTelefoon(m.getTelefoon())
                && validateEmail(m.getEmail());
    }

    private boolean validateNaam (String naam) {
        return naam != null && !naam.isEmpty();
    }

    private boolean validateAdres (String adres) {
        return adres != null && !adres.isEmpty();
    }

    private boolean validateTelefoon (String telefoon) {
        return telefoon != null && !telefoon.isEmpty();
    }

    private boolean validateEmail (String email) {
        if (email == null || email.isEmpty()) return false;
        return email.contains("@");
    }
}
