package com.brielage.uitleendienst.models;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable (tableName = "beschikbaarItem")
public class BeschikbaarItem {
    private String          id;
    private String          uitleenbaarItemId;
    private String          magazijnId;
    private int             aantalTotaal;
    private int             aantalBeschikbaar;
    private int             aantalGereserveerd;

    public BeschikbaarItem () {}

    public BeschikbaarItem (
            String uitleenbaarItemId,
            String magazijnId,
            int aantalTotaal,
            int aantalBeschikbaar,
            int aantalGereserveerd) {
        this.uitleenbaarItemId  = uitleenbaarItemId;
        this.magazijnId         = magazijnId;
        this.aantalTotaal       = aantalTotaal;
        this.aantalBeschikbaar  = aantalBeschikbaar;
        this.aantalGereserveerd = aantalGereserveerd;
    }

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId () {
        return id;
    }

    @DynamoDBAttribute
    public void setId (String id) {
        this.id = id;
    }

    @DynamoDBAttribute
    public String getUitleenbaarItemId () {
        return uitleenbaarItemId;
    }

    @DynamoDBAttribute
    public void setUitleenbaarItemId (String uitleenbaarItemId) {
        this.uitleenbaarItemId = uitleenbaarItemId;
    }

    @DynamoDBAttribute
    public String getMagazijnId () {
        return magazijnId;
    }

    @DynamoDBAttribute
    public void setMagazijnId (String magazijnId) {
        this.magazijnId = magazijnId;
    }

    @DynamoDBAttribute
    public int getAantalTotaal () {
        return aantalTotaal;
    }

    @DynamoDBAttribute
    public void setAantalTotaal (int aantalTotaal) {
        this.aantalTotaal = aantalTotaal;
    }

    @DynamoDBAttribute
    public int getAantalBeschikbaar () {
        return aantalBeschikbaar;
    }

    @DynamoDBAttribute
    public void setAantalBeschikbaar (int aantalBeschikbaar) {
        this.aantalBeschikbaar = aantalBeschikbaar;
    }

    @DynamoDBAttribute
    public int getAantalGereserveerd () {
        return aantalGereserveerd;
    }

    @DynamoDBAttribute
    public void setAantalGereserveerd (int aantalGereserveerd) {
        this.aantalGereserveerd = aantalGereserveerd;
    }

    @Override
    public String toString () {
        return "BeschikbaarItem{" +
                "id='" + id + '\'' +
                ", uitleenbaarItemId=" + uitleenbaarItemId +
                ", magazijnId=" + magazijnId +
                ", aantalTotaal=" + aantalTotaal +
                ", aantalBeschikbaar=" + aantalBeschikbaar +
                ", aantalGereserveerd=" + aantalGereserveerd +
                '}';
    }

    @Override
    public boolean equals(Object o){
        if(o instanceof BeschikbaarItem bi){
            return this.getId().equals(bi.getId());
        }
        return false;
    }
}
