package com.brielage.uitleendienst.models;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable (tableName = "contactMagazijn")
public class ContactMagazijn {
    private String id;
    private String persoonId;
    private String magazijnId;
    private String opmerking;

    public ContactMagazijn () {}

    public ContactMagazijn (
            String persoonId,
            String magazijnId,
            String opmerking) {
        this.persoonId  = persoonId;
        this.magazijnId = magazijnId;
        this.opmerking  = opmerking;
    }

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId () {return id;}

    @DynamoDBAttribute
    public void setId (String id) {this.id = id;}

    @DynamoDBAttribute
    public String getPersoonId () {return persoonId;}

    @DynamoDBAttribute
    public void setPersoonId (final String persoonId) {this.persoonId = persoonId;}

    @DynamoDBAttribute
    public String getMagazijnId () {return magazijnId;}

    @DynamoDBAttribute
    public void setMagazijnId (final String magazijnId) {this.magazijnId = magazijnId;}

    @DynamoDBAttribute
    public String getOpmerking () {return opmerking;}

    @DynamoDBAttribute
    public void setOpmerking (String opmerking) {this.opmerking = opmerking;}

    @Override
    public String toString () {
        return "ContactMagazijn{" +
                "id='" + id + '\'' +
                ", persoonId=" + persoonId +
                ", magazijnId=" + magazijnId +
                ", opmerking='" + opmerking + '\'' +
                '}';
    }
}
