package com.brielage.uitleendienst.models;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable (tableName = "contactHuurder")
public class ContactHuurder {
    private String      id;
    private String      persoonId;
    private String      organisatieId;
    private String      opmerking;

    public ContactHuurder () {}

    public ContactHuurder (
            String persoonId,
            String organisatieId,
            String opmerking) {
        this.persoonId = persoonId;
        this.organisatieId = organisatieId;
        this.opmerking   = opmerking;
    }

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId () {
        return id;
    }

    @DynamoDBAttribute
    public void setId (String id) {
        this.id = id;
    }

    @DynamoDBAttribute
    public String getPersoonId() {
        return persoonId;
    }

    @DynamoDBAttribute
    public void setPersoonId(String persoonId) {
        this.persoonId = persoonId;
    }

    @DynamoDBAttribute
    public String getOrganisatieId() {
        return organisatieId;
    }

    @DynamoDBAttribute
    public void setOrganisatieId(String organisatieId) {
        this.organisatieId = organisatieId;
    }

    @DynamoDBAttribute
    public String getOpmerking () {
        return opmerking;
    }

    @DynamoDBAttribute
    public void setOpmerking (String opmerking) {
        this.opmerking = opmerking;
    }

    @Override
    public String toString () {
        return "ContactHuurder{" +
                "id='" + id + '\'' +
                ", persoonId=" + persoonId +
                ", organisatieId=" + organisatieId +
                ", opmerking='" + opmerking + '\'' +
                '}';
    }

    @Override
    public boolean equals(Object o){
        if(o instanceof ContactHuurder ch){
            return this.getId().equals(ch.getId());
        }
        return false;
    }
}
