package com.brielage.uitleendienst.models;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable (tableName = "uitlening")
public class Uitlening {
    private String id;
    private String persoonId;
    private String magazijnId;
    private String start;
    private String eind;
    private String teruggebrachtOp;
    private String opmerking;

    public Uitlening () {}

    public Uitlening (
            String persoonId,
            String magazijnId,
            String start,
            String eind,
            String teruggebrachtOp,
            String opmerking) {
        this.persoonId       = persoonId;
        this.magazijnId      = magazijnId;
        this.start           = start;
        this.eind            = eind;
        this.teruggebrachtOp = teruggebrachtOp;
        this.opmerking       = opmerking;
    }

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId () {
        return id;
    }

    @DynamoDBAttribute
    public void setId (String id) {
        this.id = id;
    }

    @DynamoDBAttribute
    public String getPersoonId () {return persoonId;}

    @DynamoDBAttribute
    public void setPersoonId (final String persoonId) {this.persoonId = persoonId;}

    @DynamoDBAttribute
    public String getMagazijnId () {
        return magazijnId;
    }

    @DynamoDBAttribute
    public void setMagazijnId (String magazijnId) {
        this.magazijnId = magazijnId;
    }

    @DynamoDBAttribute
    public String getStart () {
        return start;
    }

    @DynamoDBAttribute
    public void setStart (String start) {this.start = start;}

    @DynamoDBAttribute
    public String getEind () {
        return eind;
    }

    @DynamoDBAttribute
    public void setEind (String eind) {
        this.eind = eind;
    }

    @DynamoDBAttribute
    public String getTeruggebrachtOp () {
        return teruggebrachtOp;
    }

    @DynamoDBAttribute
    public void setTeruggebrachtOp (String teruggebrachtOp) {
        this.teruggebrachtOp = teruggebrachtOp;
    }

    @DynamoDBAttribute
    public String getOpmerking () {
        return opmerking;
    }

    @DynamoDBAttribute
    public void setOpmerking (String opmerking) {
        this.opmerking = opmerking;
    }

    @Override
    public String toString () {
        return "Uitlening{" +
                "id='" + id + '\'' +
                ", persoonId='" + persoonId + '\'' +
                ", magazijnId='" + magazijnId + '\'' +
                ", start='" + start + '\'' +
                ", eind='" + eind + '\'' +
                ", teruggebrachtOp='" + teruggebrachtOp + '\'' +
                ", opmerking='" + opmerking + '\'' +
                '}';
    }

    @Override
    public boolean equals (Object o) {
        if (o instanceof Uitlening u)
            return this.getId()
                       .equals(u.getId());

        return false;
    }
}
