package com.brielage.uitleendienst.models;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable (tableName = "uitleningItem")
public class UitleningItem {
    private String id;
    private String uitleningId;
    private String uitleenbaarItemId;
    private int    aantal;
    private String teruggebrachtOp;
    private int    aantalTeruggebracht;

    public UitleningItem () {}

    public UitleningItem (
            final String id,
            final String uitleningId,
            final String uitleenbaarItemId,
            final int aantal,
            final String teruggebrachtOp,
            final int aantalTeruggebracht) {
        this.id                  = id;
        this.uitleningId         = uitleningId;
        this.uitleenbaarItemId   = uitleenbaarItemId;
        this.aantal              = aantal;
        this.teruggebrachtOp     = teruggebrachtOp;
        this.aantalTeruggebracht = aantalTeruggebracht;
    }

    public UitleningItem (
            String uitleningId,
            String uitleenbaarItemId,
            int aantal,
            String teruggebrachtOp,
            int aantalTeruggebracht) {
        this.uitleningId         = uitleningId;
        this.uitleenbaarItemId   = uitleenbaarItemId;
        this.aantal              = aantal;
        this.teruggebrachtOp     = teruggebrachtOp;
        this.aantalTeruggebracht = aantalTeruggebracht;
    }

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId () {return id;}

    @DynamoDBAttribute
    public void setId (final String id) {this.id = id;}

    @DynamoDBAttribute
    public String getUitleningId () {return uitleningId;}

    @DynamoDBAttribute
    public void setUitleningId (final String uitleningId) {this.uitleningId = uitleningId;}

    @DynamoDBAttribute
    public String getUitleenbaarItemId () {return uitleenbaarItemId;}

    @DynamoDBAttribute
    public void setUitleenbaarItemId (final String uitleenbaarItemId) {this.uitleenbaarItemId = uitleenbaarItemId;}

    @DynamoDBAttribute
    public int getAantal () {return aantal;}

    @DynamoDBAttribute
    public void setAantal (final int aantal) {this.aantal = aantal;}

    @DynamoDBAttribute
    public String getTeruggebrachtOp () {return teruggebrachtOp;}

    @DynamoDBAttribute
    public void setTeruggebrachtOp (final String teruggebrachtOp) {this.teruggebrachtOp = teruggebrachtOp;}

    @DynamoDBAttribute
    public int getAantalTeruggebracht () {return aantalTeruggebracht;}

    @DynamoDBAttribute
    public void setAantalTeruggebracht (final int aantalTeruggebracht) {this.aantalTeruggebracht = aantalTeruggebracht;}

    @Override
    public String toString () {
        return "UitleningItem{" +
                "id='" + id + '\'' +
                ", uitleningId='" + uitleningId + '\'' +
                ", uitleenbaarItemId='" + uitleenbaarItemId + '\'' +
                ", aantal=" + aantal +
                ", teruggebrachtOp='" + teruggebrachtOp + '\'' +
                ", aantalTeruggebracht=" + aantalTeruggebracht +
                '}';
    }

    @Override
    public boolean equals (Object o) {
        if (o instanceof UitleningItem ui)
            return this.getId()
                       .equals(ui.getId());

        return false;
    }
}
