package com.brielage.uitleendienst.models;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable (tableName = "user")
public class User {
    private String id;
    private String username;
    private String rolId;
    private String persoonId;

    public User () {}

    public User (
            String username,
            String rolId,
            String persoonId) {
        this.username = username;
        this.rolId     = rolId;
        this.persoonId = persoonId;
    }

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId () {
        return id;
    }

    @DynamoDBAttribute
    public void setId (String id) {
        this.id = id;
    }

    @DynamoDBAttribute
    public String getUsername () {
        return username;
    }

    @DynamoDBAttribute
    public void setUsername (String username) {
        this.username = username;
    }

    @DynamoDBAttribute
    public String getRolId () {return rolId;}

    @DynamoDBAttribute
    public void setRolId (final String rolId) {this.rolId = rolId;}

    @DynamoDBAttribute
    public String getPersoonId () {return persoonId;}

    @DynamoDBAttribute
    public void setPersoonId (final String persoonId) {this.persoonId = persoonId;}

    @Override
    public String toString () {
        return "User{" +
                "id='" + id + '\'' +
                ", username='" + username + '\'' +
                ", rolId=" + rolId +
                ", persoonId=" + persoonId +
                '}';
    }

    @Override
    public boolean equals(Object o){
        if(o instanceof User u){
            return this.getId().equals(u.getId());
        }
        return false;
    }
}
