package com.brielage.uitleendienst.models;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable (tableName = "verantwoordelijkeMagazijn")
public class VerantwoordelijkeMagazijn {
    private String   id;
    private String persoonId;
    private String magazijnId;

    public VerantwoordelijkeMagazijn () {}

    public VerantwoordelijkeMagazijn (
            String persoonId,
            String magazijnId) {
        this.persoonId = persoonId;
        this.magazijnId = magazijnId;
    }

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId () {
        return id;
    }

    @DynamoDBAttribute
    public void setId (String id) {
        this.id = id;
    }

    @DynamoDBAttribute
    public String getPersoonId() {
        return persoonId;
    }

    @DynamoDBAttribute
    public void setPersoonId(String persoonId) {
        this.persoonId = persoonId;
    }

    @DynamoDBAttribute
    public String getMagazijnId() {
        return magazijnId;
    }

    @DynamoDBAttribute
    public void setMagazijnId(String magazijnId) {
        this.magazijnId = magazijnId;
    }

    @Override
    public String toString () {
        return "VerantwoordelijkeMagazijn{" +
                "id='" + id + '\'' +
                ", persoonId=" + persoonId +
                ", magazijnId=" + magazijnId +
                '}';
    }

    @Override
    public boolean equals(Object o){
        if(o instanceof VerantwoordelijkeMagazijn vm){
            return this.getId().equals(vm.getId());
        }
        return false;
    }
}
