package com.brielage.uitleendienst.models;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

@DynamoDBTable(tableName = "verantwoordelijkeMagazijn")
public class VerantwoordelijkeMagazijn {
    private String id;
    private Persoon persoon;
    private Magazijn magazijn;

    public VerantwoordelijkeMagazijn() {
    }

    public VerantwoordelijkeMagazijn(Persoon persoon, Magazijn magazijn) {
        this.persoon = persoon;
        this.magazijn = magazijn;
    }

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    @DynamoDBAttribute
    public void setId(String id) {
        this.id = id;
    }

    @DynamoDBAttribute
    public Persoon getPersoon() {
        return persoon;
    }

    @DynamoDBAttribute
    public void setPersoon(Persoon persoon) {
        this.persoon = persoon;
    }

    @DynamoDBAttribute
    public Magazijn getMagazijn() {
        return magazijn;
    }

    @DynamoDBAttribute
    public void setMagazijn(Magazijn magazijn) {
        this.magazijn = magazijn;
    }
}
